baseurl = "https://stephanjacobs.io"
title = "Stephan Jacobs"
author = "Stephan Jacobs"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "Stephan Jacobs"

[[menu.main]]
    name = "Home"
    url = "https://stephanjacobs.io"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/stephan-jacobs"
    weight = 2
